export const dataDocuments = () => {
    return [
        "Literatura en Historia",
"Filosofía",
"Lenguas extranjeras",
"Arte",
"Música",
"Danza",
"Teatro",
"Publicidad y Relaciones Públicas",
"Periodismo",
"Comunicación Social",
"Psicología",
"Sociología",
"Antropología",
"Derecho",
"Ciencias Sociales",
"Finanzas",
"Contabilidad",
"Administración de Empresas",
"Relaciones Internacionales",
"Ciencias de la Comunicación",
"Periodismo",
"Publicidad y Relaciones Públicas",
"Física",
"Química",
"Biología",
"Matemáticas",
"Estadística",
"Informática",
"Ingeniería",
"Ciencias de la Computación",
"Ciencias de la Tierra",
"Ciencias Ambientales",
"Medicina",
"Enfermería",
"Farmacia",
"Odontología",
"Fisioterapia",
"Terapia Ocupacional",
"Logopedia",
"Nutrición",
"Ingeniería Mecánica",
"Ingeniería Eléctrica",
"Ingeniería Electrónica",
"Ingeniería Informática",
"Ingeniería de Software",
"Ingeniería de Redes",
"Ingeniería de Telecomunicaciones",
"Ingeniería de Sistemas",
"Ingeniería de Energía",
"Ingeniería de Medio Ambiente",
"Ingeniería de Recursos Naturales",
"Diseño Industrial",
"Diseño Gráfico",
"Diseño de Interiores",
"Ingeniería de la Construcción",
"Ingeniería de la Producción"
    ];
}

export const AlumnosRegister = () => {
    return [
        {
            id: "20210000",
            Ap: "Dávila",
            Am: "Bartolo",
            Name: "Jasson David",
            Carrier: "Ingeniería en Sistemas Computacionales",
            FR:"20-03-2024",
            FH:"20:09:00"
        },
        {
            id: "20210001",
            Ap: "González",
            Am: "López",
            Name: "Juan José",
            Carrier: "Ingeniería Informática",
        },
        {
            id: "20210002",
            Ap: "Martínez",
            Am: "Gómez",
            Name: "María Guadalupe",
            Carrier: "Licenciatura en Administración",
        },
        {
            id: "20210003",
            Ap: "Rodríguez",
            Am: "Pérez",
            Name: "Luis Fernando",
            Carrier: "Licenciatura en Derecho",
        },
        {
            id: "20210004",
            Ap: "Hernández",
            Am: "Sánchez",
            Name: "Ana Karen",
            Carrier: "Ingeniería Civil",
        },
        {
            id: "20210005",
            Ap: "López",
            Am: "Ramírez",
            Name: "Carlos Alberto",
            Carrier: "Licenciatura en Psicología",
        },
        {
            id: "20210006",
            Ap: "Gómez",
            Am: "Fernández",
            Name: "Laura Alejandra",
            Carrier: "Licenciatura en Enfermería",
        },
        {
            id: "20210007",
            Ap: "Díaz",
            Am: "Vázquez",
            Name: "Javier",
            Carrier: "Ingeniería Industrial",
        },
       
        
    ]
}
